spring.application.name=demo

server.port=9090


#VERITABANI AYARLARI

#VERITABANI AYARLARI
spring.datasource.url=jdbc:postgresql://localhost:5432/musicdb
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1500
spring.data.redis.connect-timeout=1000
#spring.data.redis.password=

app.cache.search-ttl-minutes=360
app.cache.recommend-ttl-minutes=1440
app.cache.music-ttl-minutes=30

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.properties.mail.smtp.auth=true


spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

spring.mail.properties.mail.smtp.localhost=localhost


